# Configuration for Stale Bot to keep the repository clean
# https://github.com/actions/stale

name: "Mark stale issues and pull requests"

on:
  schedule:
    - cron: "0 0 * * *"  
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Mark stale issues and PRs
        uses: actions/stale@v6
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 14
          days-before-close: 28
          stale-issue-message: "💤 This issue has been inactive for 14 days. It will be closed automatically if no further activity occurs. Feel free to comment to keep it open!"
          stale-pr-message: "💤 This pull request has been inactive for 14 days. It will be closed automatically if no further activity occurs. Please update or comment to keep it active!"
          exempt-issue-labels: "pinned,security-review"
          exempt-pr-labels: "work-in-progress,do-not-close"
          only-labels: ""
          stale-issue-label: "stale"
          stale-pr-label: "stale"
          remove-stale-when-updated: true
