version: 1

policies:
  - name: "Standard Contribution Policy"
    description: "Ensures all pull requests follow contribution standards and pass moderation checks."

    approval:
      method: "PR Review"
      required_count: 1
      users:
        - MilesONerd
      allow_author: false

    approval_rules:
      - name: Require review or bot approval
        requires:
          count: 1
          reviewers: ["MilesONerdBot"]

    conditions:
      must_not_have_labels:
        - "spam"
        - "ai-generated"
        - "needs-human-review"
      require_branch_up_to_date: true
      require_status_success: true
      require_no_conflicts: true

    actions:
      on_approval:
        - type: "status"
          state: "success"
          description: "✅ All policy checks passed and human approval received."

